window['strings'] =
{
	// strings for warning panel **********************************************************************************
	'STR_PANEL2_WARNING' : { 'size' : 35, 'font' : 'Arial', 'align' : 'left', 'style' : 'bold',
								 'fill' : '0x0000', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : 'Advertencia!' },
	'STR_PANEL2_WARNING_INFO' : { 'size' : 18, 'font' : 'Arial', 'align' : 'left', 'style' : 'bold',
								 'fill' : '0x000000', 'wordWrap' : true, 'wordWrapWidth' : 240, 'style' : 'normal',
								'text' : 'No apto para votantes desinformados. Visita http://www.jne.gob.pe/' },
	// ************************************************************************************************************
	'STR_PANEL1_SCENE_INFO' : { 'size' : 20, 'font' : 'Arial', 'align' : 'left', 'style': 'bold',
								'fill' : '0x000000', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : 'No apto para votantes desinformados.\n\r Visita http://www.jne.gob.pe/' },

	'STR_TEAM_NAME' : { 'size' : 40, 'font' : 'Arial', 'align' : 'center', 'style' : 'bold',
						'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
						'text' : 'DEMOCRACIA TEAM \n\r PRESENTA' },
	// ************************************************************************************************************
	'STR_TEAM_NAME_1' : { 'size' : 50, 'font' : 'Arial', 'align' : 'center', 'style' : 'bold',
						  'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
						'text' : 'DEMOCRACIA TEAM' },
	'STR_TEAM_NAME_2' : { 'size' : 20, 'font' : 'Arial', 'align' : 'center', 'style' : 'bold',
						  'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
						  'text' : 'PRESENTA' },
	'STR_PATRIOTA' : { 'size' : 30, 'font' : 'Arial', 'align' : 'center', 'style' : 'bold',
						  'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
						  'text' : 'PATRIOTA' },
	// ************************************************************************************************************
	'STR_PANEL4_STORY_1' : { 'size' : 35, 'font' : 'Arial', 'align' : 'left', 'style': 'normal',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : 'Eres nombrado Presidente de la' },
	'STR_PANEL4_STORY_2' : { 'size' : 35, 'font' : 'Arial', 'align' : 'left', 'style': 'normal',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : 'República del Perú y aquí' },
	'STR_PANEL4_STORY_3' : { 'size' : 35, 'font' : 'Arial', 'align' : 'left', 'style': 'normal',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : 'comienza tu historia.' },
	// ************************************************************************************************************
	'STR_PANEL5_STORY_1' : { 'size' : 35, 'font' : 'Arial', 'align' : 'left', 'style': 'normal',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : 'Buenos días Sr. Presidente,' },
	'STR_PANEL5_STORY_2' : { 'size' : 35, 'font' : 'Arial', 'align' : 'left', 'style': 'normal',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : 'tiene una llamada por la línea' },
	'STR_PANEL5_STORY_3' : { 'size' : 35, 'font' : 'Arial', 'align' : 'left', 'style': 'normal',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : 'dos de emergencia.' },
	// ************************************************************************************************************
	'STR_PANEL7_STORY_1' : { 'size' : 35, 'font' : 'Arial', 'align' : 'left', 'style': 'normal',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : '"Buenos días Sr. Presidente,' },
	'STR_PANEL7_STORY_2' : { 'size' : 35, 'font' : 'Arial', 'align' : 'left', 'style': 'normal',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : 'soy el Secretario de las' },
	'STR_PANEL7_STORY_3' : { 'size' : 35, 'font' : 'Arial', 'align' : 'left', 'style': 'normal',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : 'Misiones Imposibles, sé que le' },
	'STR_PANEL7_STORY_4' : { 'size' : 35, 'font' : 'Arial', 'align' : 'left', 'style': 'normal',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : 'extrañará mi llamada'},
	'STR_PANEL7_STORY_5' : { 'size' : 35, 'font' : 'Arial', 'align' : 'left', 'style': 'normal',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : 'Lamentablemente no tengo'},
	'STR_PANEL7_STORY_6' : { 'size' : 35, 'font' : 'Arial', 'align' : 'left', 'style': 'normal',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : 'buenas noticias..."'},
	// ************************************************************************************************************
	'STR_PANEL8_DOTS' : { 'size' : 100, 'font' : 'Arial', 'align' : 'center', 'style': 'bold',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : '...' },
	'STR_PANEL8_STORY' : { 'size' : 20, 'font' : 'Arial', 'align' : 'center', 'style' : 'normal',
						'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
						'text' : '(el silencio te agobia manteniendo la expectativa)' },
	// ************************************************************************************************************
	'STR_PANEL9_STORY_1' : { 'size' : 35, 'font' : 'Arial', 'align' : 'left', 'style': 'normal',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : '"Tenemos una alerta mundial y' },
	'STR_PANEL9_STORY_2' : { 'size' : 35, 'font' : 'Arial', 'align' : 'left', 'style': 'normal',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : 'necesitamos su ayuda..."' },
	// ************************************************************************************************************
	'STR_PANEL10_STORY_1' : { 'size' : 35, 'font' : 'Arial', 'align' : 'left', 'style': 'normal',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : '"Disculpa la interrupción, ha' },
	'STR_PANEL10_STORY_2' : { 'size' : 35, 'font' : 'Arial', 'align' : 'left', 'style': 'normal',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : 'llegado un sobre clasificado' },
	'STR_PANEL10_STORY_3' : { 'size' : 35, 'font' : 'Arial', 'align' : 'center', 'style': 'normal',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : 'para Usted..."' },
	// ************************************************************************************************************
	'STR_PANEL11_STORY_1' : { 'size' : 35, 'font' : 'Arial', 'align' : 'left', 'style': 'normal',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : '"Tiene sólo una hora para' },
	'STR_PANEL11_STORY_2' : { 'size' : 35, 'font' : 'Arial', 'align' : 'left', 'style': 'normal',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : 'designar a su mejor reemplazo,' },
	'STR_PANEL11_STORY_3' : { 'size' : 35, 'font' : 'Arial', 'align' : 'left', 'style': 'normal',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : 'un avión pasará por usted.' },
	'STR_PANEL11_STORY_4' : { 'size' : 35, 'font' : 'Arial', 'align' : 'left', 'style': 'normal',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : 'Recuerde, en sus manos está'},
	'STR_PANEL11_STORY_5' : { 'size' : 35, 'font' : 'Arial', 'align' : 'left', 'style': 'normal',
								'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
								'text' : 'hacer la mejor elección."'},
  // ************************************************************************************************************
	'STR_PANEL12_STORY' : { 'size' : 17, 'font' : 'Arial', 'align' : 'left', 'style': 'normal',
								'fill' : '0x000000', 'wordWrap' : true, 'wordWrapWidth' : 580,
								'text' : 'Son 14 los candidatos, quienes fueron sus contendores en las elecciones pasadas, tendrá que seleccionar a solo 5, el primero que elija deberá ser su favorito.\n\nEligirá cual es la mejor propuesta para cada uno de los 6 pilares, previamente deverá indicar tres de ellos, los cuales aseguran el desarrollo de la nación. Las propuestas seleccionadas en cada pilar deberían de ser las de su favorito. Sabemos que Ud. se encuentra informado y conoce muy bien lo que él o ella propone. \n\n Al final se conocerá quien asumirá su cargo, si el personaje que sale luego de su elección es su favorito Ud. podrá retornar a ocupar su cargo, en caso contrario Ud. no podrá volver a tomar su cargo, a postular o a ser elegible para una próxima presidencia, lo mismo  ocurrirá con su candidato favorito.'},
  // ************************************************************************************************************
	'STR_QUESTION_TITTLE' : { 'size' : 25, 'font' : 'Arial', 'align' : 'left', 'style' : 'bold',
						  	  'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
						  	  'text' : 'PREGUNTA' },
	'STR_QUESTION_GENERIC' : { 'size' : 15, 'font' : 'Arial', 'align' : 'left', 'style' : 'normal',
						  	   'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
						  	   'text' : 'Propuesta ...' },
  // ************************************************************************************************************
  	'STR_WINNER_NAME': { 'size' : 25, 'font' : 'Arial', 'align' : 'left', 'style' : 'bold',
						  	  'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
						  	  'text' : 'NOMBRE:' },
	'STR_WINNER_PARTY': { 'size' : 25, 'font' : 'Arial', 'align' : 'left', 'style' : 'bold',
						  	  'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
						  	  'text' : 'PARTIDO:' },
	'STR_WINNER_PROFESSION': { 'size' : 25, 'font' : 'Arial', 'align' : 'left', 'style' : 'bold',
						  	  'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
						  	  'text' : 'PROFESION: ' },
	'STR_WINNER_AGE': { 'size' : 25, 'font' : 'Arial', 'align' : 'left', 'style' : 'bold',
						  	  'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
						  	  'text' : 'EDAD:' },
	'STR_WINNER_ORIGIN': { 'size' : 25, 'font' : 'Arial', 'align' : 'left', 'style' : 'bold',
						  	  'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
						  	  'text' : 'NATURAL: ' },
  // ************************************************************************************************************
	'STR_COINCIDENCES': { 'size' : 25, 'font' : 'Arial', 'align' : 'left', 'style' : 'bold',
						  	  'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
						  	  'text' : 'Coindicences:' },
	'STR_FAILS': { 'size' : 25, 'font' : 'Arial', 'align' : 'left', 'style' : 'bold',
						  	  'fill' : 'white', 'wordWrap' : false, 'wordWrapWidth' : 100,
						  	  'text' : 'Fails: ' },

}
